#!/usr/bin/env python3
"""Build-time sprite baker for the M0 bounce demo.

Emits a C header on stdout: a 4-color ball filmstrip (straight-alpha
ARGB8888) and an opaque RGB565 checker tile. Real themes come from
surfpack later; this keeps per-pixel work out of runtime code per
CLAUDE.md's frame-path rule.
"""

BALL = 64
COLORS = [(235, 90, 90), (80, 200, 220), (240, 190, 80), (170, 120, 240)]
TILE = 128
CHECKER = 16


def clamp(v):
    return max(0, min(255, int(v)))


def ball_strip():
    strip_w = BALL * len(COLORS)
    px = []
    for y in range(BALL):
        for frame, (br, bg, bb) in enumerate(COLORS):
            for x in range(BALL):
                nx = (x + 0.5) / BALL * 2.0 - 1.0
                ny = (y + 0.5) / BALL * 2.0 - 1.0
                r = (nx * nx + ny * ny) ** 0.5
                a = clamp((1.0 - r) * BALL / 2.0 * 255.0)
                shade = max(0.0, 1.0 - 0.72 * r * r)
                hx, hy = nx + 0.38, ny + 0.38
                hr = (hx * hx + hy * hy) ** 0.5
                spec = max(0.0, 1.0 - hr * 2.0) ** 3 * 230.0
                col = (clamp(br * shade + spec),
                       clamp(bg * shade + spec),
                       clamp(bb * shade + spec))
                word = (a << 24) | (col[0] << 16) | (col[1] << 8) | col[2]
                px.append((frame * BALL + x, y, word))
    out = [0] * (strip_w * BALL)
    for x, y, word in px:
        out[y * strip_w + x] = word
    return strip_w, BALL, out


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def tile():
    c1, c2, edge = (70, 74, 84), (94, 99, 112), (140, 150, 170)
    out = []
    for y in range(TILE):
        for x in range(TILE):
            if x < 2 or y < 2 or x >= TILE - 2 or y >= TILE - 2:
                c = edge
            elif ((x // CHECKER) + (y // CHECKER)) % 2 == 0:
                c = c1
            else:
                c = c2
            out.append(rgb565(*c))
    return out


def emit(name, ctype, values, per_line=12):
    print(f"static {ctype} {name}[{len(values)}] = {{")
    for i in range(0, len(values), per_line):
        row = ", ".join(f"0x{v:x}" for v in values[i:i + per_line])
        print(f"    {row},")
    print("};")


def main():
    strip_w, strip_h, strip = ball_strip()
    print("/* Generated by tools/gen_demo_assets.py — do not edit. */")
    print(f"#define BOUNCE_BALL_SIZE {BALL}")
    print(f"#define BOUNCE_BALL_FRAMES {len(COLORS)}")
    print(f"#define BOUNCE_STRIP_W {strip_w}")
    print(f"#define BOUNCE_STRIP_H {strip_h}")
    print(f"#define BOUNCE_TILE_SIZE {TILE}")
    emit("bounce_balls_px", "uint32_t", strip)
    emit("bounce_tile_px", "uint16_t", tile())


if __name__ == "__main__":
    main()
