#!/usr/bin/env python3
"""Wrap PNG files into a python module of bytes literals, so demo assets
travel the same way on every port (unix path, P4 frozen, web frozen).

  python3 tools/pngwrap.py NAME=path.png ... > out.py
"""
import sys


def main():
    print("# generated by tools/pngwrap.py — do not edit")
    print("# sprites: Kenney 'Space Shooter Redux', CC0 (assets/kenney/)")
    for arg in sys.argv[1:]:
        name, path = arg.split("=", 1)
        with open(path, "rb") as f:
            data = f.read()
        print("%s = %r" % (name.upper(), data))


if __name__ == "__main__":
    main()
